### ISSUE TITLE
question: allow public access to the root domain, but authenticate at the sub-domains

### ISSUE THREAD

**Issue by Nyarumi** [greenpau/caddy-security#257]
I run Caddy using **docker-compose** and a Dockerfile to install caddy-security.

I have Caddy set up to authenticate for various sub-domains, which works fine. I also have the root domain set to be publicly available and serve a static website. This also functions fine, but the **log is spammed with an error roughly every second** about a token error. Everything functions fine, but I there must be something I'm doing wrong if it continuously throws an error.

I have no previous Caddy knowledge and this setup is the product of a few hours of research and experimenting, so I've probably done something dumb with it but I can't seem to figure it out by myself.

My Caddyfile:
```
{
	order authenticate before respond
	order authorize before reverse_proxy

	security {
		local identity store localdb {
			realm local
			path /etc/caddy/auth/local/users.json
		}
        authentication portal the-portal {
    	    enable identity store localdb
            cookie domain example.com
            cookie lifetime 604800
            ui {
                links {
                    "Plex" https://plex.example.com icon "las la-tv"
                    ...
               }
            }
            transform user {
                match email youremail@mydomain.com
                action add role authp/user
            }
        }
        authorization policy admin_policy {
           set auth url https://auth.example.com
           allow roles authp/admin
        }
    }
}

auth.example.com {
    authenticate with the-portal
}

example.com {
    root * /srv
    file_server
}

plex.example.com {
    authorize with admin_policy
    reverse_proxy example:32400
}
...
```

And my compose.yml just in case:
```
version: "3.9"

services:
  caddy:
    image: caddy:2.7.2
    restart: unless-stopped
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./local:/etc/caddy/auth/local
    networks:
      - rp

    ...

networks:
  rp:
    name: reverse-proxy
    external: true 
```
